### ISSUE TITLE
[TODO] Update the recent CPython mentions to `3.11`

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-test-gh-action#45]
* [x] https://github.com/ansible-community/ansible-test-gh-action/blob/70aaefa/action.yml#L147
* [x] https://github.com/ansible-community/ansible-test-gh-action/blob/70aaefa/action.yml#L140
* [x] And maybe update the examples here https://github.com/ansible-community/ansible-test-gh-action/blob/main/README.md#usage

**Comment by felixfontein** [comment]
Maybe we should move https://github.com/ansible-community/ansible-test-gh-action/blob/70aaefa/action.yml#L140 below the map, so that the two 'latest' Python versions are closer to each other in there.

**Comment by webknjaz** [comment]
Or put `devel` into the map and use `python_version_map['devel']` as a fallback, or even go for `max(set(python_version_map.values()))`. For the latter, it'd probably be more convenient to start storing versions as tuples.

**Comment by webknjaz** [comment]
This is partially addressed by https://github.com/ansible-community/ansible-test-gh-action/pull/60.
